using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

[assembly: AssemblyTitle("Abp.AspNetZeroCore.Fixed")]
[assembly: AssemblyDescription("Abp.AspNetZeroCore.Fixed")]
[assembly: AssemblyProduct("Abp.AspNetZeroCore.Fixed")]
[assembly: AssemblyCompany("Allen")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")]
[assembly: Guid("1b81252e-937c-464e-8424-8b17b0635017")]
[assembly: AssemblyCopyright("Abp")]
[assembly: AssemblyFileVersion("3.0.0.0")]
[assembly: AssemblyInformationalVersion("3.0.0")]
[assembly: AssemblyVersion("3.0.0.0")]
